services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kanban_db"]
      interval: 3s
      timeout: 15s
      retries: 5

  kanban-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/kanban_db
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
